version: '3.8'
services:
  postgres:
    env_file:
      - .env
    image: postgres:15-alpine
    container_name: postgres-bulk-insert
    ports:
      - "${POSTGRES_PORT}:5432"
    command: postgres -c log_statement=all -c logging_collector=off
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}