version: '3.8'
services:
  postgres:
    env_file:
      - .env
    image: postgres:15-alpine
    container_name: postgres-bulk-insert
    ports:
      - "${POSTGRES_PORT}:5432"
    command: postgres -c log_statement=none -c logging_collector=off -c log_parameter_max_length=-1 -c log_duration=off -c wal_level=minimal
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}